### ISSUE TITLE
[Continuous] Fix TODOs & implement and fix tests

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/nalaf#60]

**Comment by jmcejuela** [comment]
Copied description until now:

* [x] Alex fix his
* [ ] Alex writes tests for whatever appropriate
* [x] Carsten fix his
* [ ] Carsten writes tests for whatever appropriate


Conclusions:
* Original #TODO: if possible, change parts & sentences & tokens from List to Tuple --> Deciding against this since the only real benefit was hash-ability (which turns out we can't have with mutable elements inside the tuple), additionally after some reading lists make more sense semantically for what we are doing

**Comment by juanmirocks** [comment]
Close for now
